import React, { ReactElement } from "react";
import { DashboardLayout } from "@components/layouts/dashboardLayout";

const About = () => {
  return (
    <div>
      <liwwj></liwwj>
      <liwwj></liwwj>
      <liwwj></liwwj>
      <liwwj></liwwj>
      <liwwj></liwwj>
      <liwwj></liwwj>
      <liwwj></liwwj>
      <liwwj></liwwj>
      <liwwj></liwwj>
      <liwwj></liwwj>
      <liwwj></liwwj>
      <liwwj></liwwj>
      <liwwj></liwwj>
      <liwwj></liwwj>
      <liwwj></liwwj>
      <liwwj></liwwj>
      <liwwj></liwwj>
      <liwwj></liwwj>
      <liwwj></liwwj>
      <liwwj></liwwj>
      <liwwj></liwwj>
      <liwwj></liwwj>
      <liwwj></liwwj>
      <liwwj></liwwj>
      <liwwj></liwwj>
      <liwwj></liwwj>
      <liwwj></liwwj>
      <liwwj></liwwj>
      <liwwj></liwwj>
      <liwwj></liwwj>
      <liwwj></liwwj>
      <liwwj></liwwj>
      <liwwj></liwwj>
      <liwwj></liwwj>
      <liwwj></liwwj>
      <liwwj></liwwj>
      <liwwj></liwwj>
      <liwwj></liwwj>
      <liwwj></liwwj>
      <liwwj></liwwj>
      <liwwj></liwwj>
      <liwwj></liwwj>
      <liwwj></liwwj>
      <liwwj></liwwj>
      <liwwj></liwwj>
      <liwwj></liwwj>
      <liwwj></liwwj>
      <liwwj></liwwj>
      <liwwj></liwwj>
      <liwwj></liwwj>
      <liwwj></liwwj>
      <liwwj></liwwj>
      <liwwj></liwwj>
      <liwwj></liwwj>
      <liwwj></liwwj>
      <liwwj></liwwj>
      <liwwj></liwwj>
      <liwwj></liwwj>
      <liwwj></liwwj>
      <liwwj></liwwj>
      <liwwj></liwwj>
      <liwwj></liwwj>
      <liwwj></liwwj>
      <liwwj></liwwj>
      <liwwj></liwwj>
      <liwwj></liwwj>
      <liwwj></liwwj>
      <liwwj></liwwj>
      <liwwj></liwwj>
      <liwwj></liwwj>
      <liwwj></liwwj>
      <liwwj></liwwj>
      <liwwj></liwwj>
      <liwwj></liwwj>
      <liwwj></liwwj>
      <liwwj></liwwj>
      <liwwj></liwwj>
      <liwwj></liwwj>
      <liwwj></liwwj>
      <liwwj></liwwj>
      <liwwj></liwwj>
      <liwwj></liwwj>
      <liwwj></liwwj>
      <liwwj></liwwj>
      <liwwj></liwwj>
      <liwwj></liwwj>
      <liwwj></liwwj>
      <liwwj></liwwj>
      <liwwj></liwwj>
      <liwwj></liwwj>
      <liwwj></liwwj>
      <liwwj></liwwj>
      <liwwj></liwwj>
      <liwwj></liwwj>
      <liwwj></liwwj>
      <liwwj></liwwj>
      <liwwj></liwwj>
      <liwwj></liwwj>
      <liwwj></liwwj>
      <liwwj></liwwj>
    </div>
  );
};

About.getLayout = function getLayout(page: ReactElement) {
  return <DashboardLayout>{page}</DashboardLayout>;
};

export default About;
